### ISSUE TITLE
Converting script error

### ISSUE THREAD

**Issue by pxalcantara** [Dave-Elec/freecad_to_gazebo#3]
I'm having some problems and I don't know if I'm doing something wrong. When I try to convert the script I got this:

```log
px@px:scripts (master)$ freecad2gazebo ../models/quimera#2_a2p.FCStd .
Traceback (most recent call last):
  File "/home/px/flexbe_ws/devel/bin/freecad2gazebo", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/px/flexbe_ws/src/freecad_to_gazebo/scripts/freecad2gazebo", line 4, in <module>
    from freecad_to_gazebo import freecad_exporter
  File "/home/px/flexbe_ws/devel/lib/python2.7/dist-packages/freecad_to_gazebo/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
AttributeError: 'module' object has no attribute 'scandir'

```

There is something that I'm missing? By the way, in the README, the: 
```
$ freecad_to_gazebo.py <assembly_file> <path/to/model_dir> --sdf-only
```
should be replaced by:
```
freecad2gazebo <assembly_file> <path/to/model_dir> --sdf-only
```
right?

**Comment by Dave-Elec** [comment]
> I'm having some problems and I don't know if I'm doing something wrong. When I try to convert the script I got this:

Sorry I wrote the project with python3 in my mind. `__init__.py` had `os.scandir`. I changed it to `os.listdir`

> By the way, in the README, the ...

Yes! I wrote the README before packaging it. I have fixed it.

**Comment by pxalcantara** [comment]
I don't know if I'm checking wrong, but it seems still using `os.scandir` in the [file](https://github.com/Dave-Elec/freecad_to_gazebo/blob/8547f5884c8bfcb5f838392fa16ea4b3c7b95afa/src/freecad_to_gazebo/__init__.py#L17)

and the error still happens here : 
```
px@px:scripts (master)$ freecad2gazebo ../models/quimera#2_a2p.FCStd ../models/
Traceback (most recent call last):
  File "/home/px/flexbe_ws/devel/bin/freecad2gazebo", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/px/flexbe_ws/src/freecad_to_gazebo/scripts/freecad2gazebo", line 4, in <module>
    from freecad_to_gazebo import freecad_exporter
  File "/home/px/flexbe_ws/devel/lib/python2.7/dist-packages/freecad_to_gazebo/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
AttributeError: 'module' object has no attribute 'scandir'
``` 
And It's updated

![image](https://user-images.githubusercontent.com/9446625/92038493-da5aca00-ed49-11ea-8ce1-4e7514b11830.png)

**Comment by Dave-Elec** [comment]
> I don't know if I'm checking wrong, but it seems still using os.scandir in the file

Oops, I thought I changed that. I did now.

Also it seems like python3.8 have dropped `platform.dist`. The main purpose of checking for distro name was to get appropriate freecad library path. I had seen some distros put the freecad libs in different places and names. I checked arch, debian and fedora now and have seen that all are the same. Will leave it there for now.

**Comment by pxalcantara** [comment]
So you're using Python 3.8?

**Comment by pxalcantara** [comment]
Now I changed and I'm using Python 3.8, and there is a different error: 

```
root@03f6de6972a0:scripts (master)# freecad2gazebo ~/home/quimera#2_a2p.FCStd . 
ubuntu /usr/lib/freecad
FreeCAD 0.18.4, Libs: 0.18.4R
No modules found in /usr/lib/freecad-python3/Mod
Traceback (most recent call last):
  File "/root/home/catkin_ws/devel/bin/freecad2gazebo", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/root/home/catkin_ws/src/freecad_to_gazebo/scripts/freecad2gazebo", line 4, in <module>
    from freecad_to_gazebo import freecad_exporter
  File "/root/home/catkin_ws/devel/lib/python3/dist-packages/freecad_to_gazebo/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 25, in <module>
  File "/root/home/catkin_ws/src/freecad_to_gazebo/src/freecad_to_gazebo/mesh_exporter.py", line 2, in <module>
    import collada
ModuleNotFoundError: No module named 'collada'

```

maybe something with my Freecad installation or path problems? I don't know. Sorry but I'm not used to Python big projects :/

**Comment by Dave-Elec** [comment]
> So you're using Python 3.8?

Yes.

> Now I changed and I'm using Python 3.8, and there is a different error:

You have to install `pycollada`.
`pip install pycollada`

**Comment by pxalcantara** [comment]
Thanks now I'm using the Python 3.8 and installed `pycollada`. I also made a [PR](https://github.com/Dave-Elec/freecad_to_gazebo/pull/4) to update the README to have these dependencies more explicitly.  

Now I'm facing this problem, is it a problem with my model? This model was not made by me it's why I'm asking
![image](https://user-images.githubusercontent.com/9446625/92542132-56f41980-f21e-11ea-8329-b47250b39b33.png)

Thanks again!

**Comment by Dave-Elec** [comment]
> Thanks now I'm using the Python 3.8

Python 3.8 is not required. I have used it with older python versions too. I will test it with different versions to properly set required python version. Also I will include `requirements.txt` after your issue is resolved.

> Now I'm facing this problem, is it a problem with my model? This model was not made by me it's why I'm asking

Can you share the model so that I can test it? I'm guessing your model have some issues.
As  I mentioned in the README, the project is very limited and not robust enough at all. I will try to come up with a better strategy to make it a more general and complete package.

**Comment by pxalcantara** [comment]
Yes sure, should I send you by e-mail? or another way ?

**Comment by Dave-Elec** [comment]
Email is fine. (dawitabate2@gmail.com)

**Comment by Dave-Elec** [comment]
I was inspecting your model. I have not tested it with a model with multiple bodies. As I was saying, the project is very limited. What I have tested it with is multiple files with single body and an assembly file containing the parts from those files. As far as I have tested it, It can support sub assemblies too. If you can split the assembly to multiple files that would work fine. In the mean time, I will try to work on it if I get enough time.

**Comment by pxalcantara** [comment]
> Python 3.8 is not required. I have used it with older python versions too. I will test it with different versions to properly set required python version. Also I will include requirements.txt after your issue is resolved.

So should I cancel the PR? 

> As far as I have tested it, It can support sub assemblies too. If you can split the assembly to multiple files that would work fine.

So, as far as I understood if I use sub assemblie more simple, like this [one](https://github.com/branilson/quimera_robot/blob/master/Mechanics/FreeCAD/quimera_structure_assy_a2p.FCStd) the package should work?  By the way, this repository is the one that I'm getting the models and trying to create the URDF for this robot
